from enum import Enum


class OrchestratorEvent(Enum):
    """
    Enum of events that the orchestrator can emit.
    """

    AGENT_READY = "agent_ready"
    """Event emitted when an agent is ready. Take the agent name as argument (`agent_name`)."""
    AGENT_STARTED = "agent_started"
    """Event emitted when an agent is started. Take the agent name as argument (`agent_name`)."""
    AGENT_TERMINATED = "agent_terminated"
    """Event emitted when an agent is terminated. Take the agent name as argument (`agent_name`)."""
    AGENT_ERROR = "agent_error"
    """Event emitted when an agent reports an error. Take the agent name and error message as arguments (`agent_name`, `error_message`)."""
    AGENT_HEARTBEAT = "agent_heartbeat"
    """Event emitted when an agent sends a heartbeat signal. Take no arguments."""


class AgentEvent(Enum):
    """
    Enum of events that an agent can emit.
    """

    AGENT_READY = "agent_ready"
    """Event emitted when the agent is ready to execute. Take no arguments."""
    AGENT_START = "agent_started"
    """Event emitted when the agent is started. Take no arguments."""
    AGENT_STOPPED = "agent_stopped"
    """Event emitted when the agent is stopped. Take no arguments."""
    AGENT_TERMINATED = "agent_terminated"
    """Event emitted when the agent is terminated. Take no arguments."""
    AGENT_ERROR = "agent_error"
    """Event emitted when the agent encounters an error. Take the error message as argument (`error_message`)."""
    AGENT_PAUSED = "agent_paused"
    """Event emitted when the agent is paused. Take no arguments."""
    AGENT_RESUMED = "agent_resumed"
    """Event emitted when the agent is resumed. Take no arguments."""
    AGENT_COMPLETED = "agent_completed"
    """Event emitted when the agent is completed. Take no arguments."""
    AGENT_IDLE = "agent_idle"
    """Event emitted when the agent is idle. Take no arguments."""
    AGENT_WORKING = "agent_working"
    """Event emitted when the agent is working. Take no arguments."""
    AGENT_CLOSE = "agent_close"
    """Event emitted when the agent is closing. Take no arguments."""
    AGENT_MESSAGE = "agent_message"
    """Event emitted when the agent sends a message. Take the message as argument (`message`)."""
    AGENT_COMMAND = "agent_command"
    """Event emitted when the agent receives a command. Take the command as argument (`command`)."""
    AGENT_COMMAND_RESPONSE = "agent_command_response"
    """Event emitted when the agent sends a response to a command. Take the response as argument (`response`)."""
    AGENT_COMMAND_ERROR = "agent_command_error"
    """Event emitted when the agent sends an error response to a command. Take the error message as argument (`error_message`)."""
    AGENT_COMMAND_COMPLETE = "agent_command_complete"
    """Event emitted when the agent sends a completion response to a command. Take no arguments."""
    AGENT_COMMAND_START = "agent_command_start"
    """Event emitted when the agent starts a command. Take the command as argument (`command`)."""
    AGENT_COMMAND_STOP = "agent_command_stop"
    """Event emitted when the agent stops a command. Take the command as argument (`command`)."""
    AGENT_HEARTBEAT = "agent_heartbeat"
    """Event emitted when the agent sends a heartbeat signal. Take no arguments."""
