site_name: PyOrchestrate
site_url: https://github.com/giulio333/PyOrchestrate
site_description: Framework multi process.
repo_url: https://github.com/giulio333/PyOrchestrate
repo_name: PyOrchestrate
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - navigation.sections
    - content.action.edit
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - navigation.path
    #- navigation.indexes
    - header.autohide
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      name: Framework

plugins:
  #- git-committers:
  #    repository: ai-team/documentazione
  #    branch: main
  #- git-authors
  #- git-revision-date-localized:
  #      enable_creation_date: true
  #      fallback_to_build_date: true
  #      type: timeago
  - awesome-pages
  - search:
      lang: it
  - autorefs
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3.10/objects.inv
            - https://pyzmq.readthedocs.io/en/latest/objects.inv
          options:
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_signature: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_labels: true
            group_by_category: true
            show_category_heading: true
            members_order: source
            show_if_no_docstring: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_root_heading: true
            show_source: true
            docstring_style: google
            allow_inspection: true
          paths: ["./src/"]

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes

validation:
  absolute_links: warn # Or 'relative_to_docs' - new in MkDocs 1.6
  omitted_files: warn
  unrecognized_links: warn

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
