[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyOrchestrate"
version = "0.2.0"
description = "PyOrchestrate"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "loguru>=0.7.3",
    "psutil>=7.0.0",
    "pydantic>=2.11.7",
    "pyzmq>=26.4.0",
    "requests>=2.32.3",
    "uvicorn>=0.35.0",
]

[project.scripts]
pyorchestrate = "PyOrchestrate.cli:main"
pyorchestrate-web = "PyOrchestrate.web_interface.server:main"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["."]
include = ["PyOrchestrate*"]
exclude = ["tests*", "docs*", "examples*", "scripts*", "logs*", "junit*", "build*", "dist*", "*.egg-info*"]
